---
- name: test if ulimit_items is set correctly
  assert:
    that:
      - ulimit_items | length > 0
      - ulimit_items is iterable
    quiet: yes
  when:
    - ulimit_items is defined

- name: test if item in ulimit_items is set correctly
  assert:
    that:
      - item.limit_item is defined
      - item.limit_item | length > 0
      - item.limit_item in ulimit_acceptable_limit_items
      - item.value is defined
      - item.value is number
    quiet: yes
  loop: "{{ ulimit_items }}"
  loop_control:
    label: "{{ item.limit_item }}"
  when:
    - ulimit_items is defined

- name: test if ulimit_domain is set correctly
  assert:
    that:
      - ulimit_domain is defined
      - ulimit_domain | length > 0
    quiet: yes

- name: test if ulimit_limit_type is set correctly
  assert:
    that:
      - ulimit_limit_type is defined
      - ulimit_limit_type | length > 0
      - ulimit_limit_type in [ "hard", "soft", "-" ]
    quiet: yes

- name: test if ulimit_dest is set correctly
  assert:
    that:
      - ulimit_dest is defined
      - ulimit_dest | length > 0
    quiet: yes

- name: test if ulimit_backup is set correctly
  assert:
    that:
      - ulimit_backup is defined
      - ulimit_backup is boolean
    quiet: yes
