---
# tasks file for ulimit

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: set ulimit value
  community.general.pam_limits:
    domain: "{{ item.domain | default(ulimit_domain) }}"
    limit_type: "{{ item.limit_type | default(ulimit_limit_type) }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
    comment: "{{ item.comment | default(omit) }}"
    dest: "{{ ulimit_dest }}"
    backup: "{{ ulimit_backup }}"
  loop: "{{ ulimit_items }}"
  loop_control:
    label: "{{ item.limit_item }}"
